alias c = "clear";
alias t = "touch";

# `alert` alias for long running commands - Use it like, `sleep 10; alert`
alias alert = "notify-send --urgency=low -i \"$( [ $? = 0 ] && echo terminal || echo error )\" \"$(history | tail -n1 | sed -e 's/^\s*[0-9]\\+\\s*//;s/[;&|]\\s*alert$//')\"";

# Useful aliases for `ls`
alias ll = "ls -alF";
alias la = "ls -A";
alias l = "ls -CF";